# Arrays

## Vectores

In [63]:
v <- c(7, 1, 5, 4, 9)
v

[1] 7 1 5 4 9

### Acceder al vector

In [64]:
v[1]       # Acceder al elemento
v[c(2, 4)] # Acceder a varios elementos
v[-3]      # Excluir elementos

[1] 7

[1] 1 4

[1] 7 1 4 9

### Operaciones

In [65]:
v1 <- c(3, 6, 2, 8, 4)
v2 <- c(1, 5, 7, 2, 9)

In [66]:
v1 + v2      # Sumar vectores
v1 * v2      # Multiplicar vectores
v1 / v2      # Dividir vectores
v1 / 2       # Dividir vector por un escalar
v1 > v2      # Comparar vectores
v1 == v2     # Comparar igualdad
v1[v1 > 4]   # Filtrar elementos mayores a 4


[1]  4 11  9 10 13

[1]  3 30 14 16 36

[1] 3.0000000 1.2000000 0.2857143 4.0000000 0.4444444

[1] 1.5 3.0 1.0 4.0 2.0

[1]  TRUE  TRUE FALSE  TRUE FALSE

[1] FALSE FALSE FALSE FALSE FALSE

[1] 6 8

### Funciones de R

In [67]:
v <- c(10, 20, 30, 40, 50)

In [68]:
length(v) # Longitud del vector
sum(v)    # Suma de elementos
mean(v)   # Promedio
max(v)    # Valor máximo
min(v)    # Valor mínimo

[1] 5

[1] 150

[1] 30

[1] 50

[1] 10

## Matrices

In [69]:
column1 <- c(1, 2, 3)
column2 <- c(4, 5, 6)
column3 <- c(7, 8, 9)
matriz <- matrix(c(column1, column2, column3), nrow = 3, ncol = 3)
matriz

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

### Argumentos principales de `matrix()`
- **`data`**: Los datos que se usarán para llenar la matriz.
- **`nrow`**: Número de filas.
- **`ncol`**: Número de columnas.
- **`byrow`**: Si es `TRUE`, llena la matriz por filas (por defecto es `FALSE`, llena por columnas).

In [70]:
matriz <- matrix(1:6, nrow = 2, ncol = 3, byrow = TRUE)
matriz

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

### Acceder a la matriz

In [71]:
matriz <- matrix(1:9, nrow = 3, ncol = 3)
matriz

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [72]:
matriz[2, 3]  # Acceder al elemento (fila 2, columna 3)
matriz[1, ]   # Acceder a la fila completa (fila 1)
matriz[, 2]   # Acceder a la columna completa (columna 2)

[1] 8

[1] 1 4 7

[1] 4 5 6

### Operaciones

In [73]:
A <- matrix(1:4, nrow = 2)
B <- matrix(5:8, nrow = 2)
A
B

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [74]:
A + B   # Suma
A - B   # Resta
A * B   # Multiplicación (elemento a elemento)
A %*% B # Producto matricial (algebra lineal)
A / B   # División (elemento a elemento)

[,1] [,2]
[1,] 6    10  
[2,] 8    12

[,1] [,2]
[1,] -4   -4  
[2,] -4   -4

[,1] [,2]
[1,]  5   21  
[2,] 12   32

[,1] [,2]
[1,] 23   31  
[2,] 34   46

[,1]      [,2]     
[1,] 0.2000000 0.4285714
[2,] 0.3333333 0.5000000

### Funciones de R

In [75]:
matriz <- matrix(1:9, nrow = 3)
matriz

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [76]:
dim(matriz)       # Dimensiones de la matriz
t(matriz)         # Transponer una matriz
rowSums(matriz)   # Suma de filas
colSums(matriz)   # Suma de columnas
rowMeans(matriz)  # Promedio de filas
colMeans(matriz)  # Promedio de columnas

[1] 3 3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[1] 12 15 18

[1]  6 15 24

[1] 4 5 6

[1] 2 5 8

### Combinar matrices

In [77]:
A <- matrix(1:4, nrow = 2)
B <- matrix(5:8, nrow = 2)
A
B

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [78]:
# Combinar por filas
matriz_filas <- rbind(A, B)
matriz_filas

[,1] [,2]
[1,] 1    3   
[2,] 2    4   
[3,] 5    7   
[4,] 6    8

In [79]:
# Combinar por columnas
matriz_columnas <- cbind(A, B)
matriz_columnas

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

### Dar nombres

In [80]:
matriz

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [81]:
colnames(matriz) <- c("column1", "column2", "column3")
rownames(matriz) <- c("row1", "row2", "row3")
matriz

column1 column2 column3
row1 1       4       7      
row2 2       5       8      
row3 3       6       9

In [82]:
matriz['row2', 'column2'] # elemento en la posición 2,2
matriz[,'column3']        # columna 3
matriz['row2',]           # fila 2

[1] 5

row1 row2 row3 
   7    8    9

column1 column2 column3 
      2       5       8