# Listas

Las listas guardan diferentes tipos de objetos en un mismo objeto R.

**Ejemplo de uso:** Regresión Lineal, errores, etc.

Inicializar variables

In [1]:
vector <- c(1, 2, 3, 4, 5)
matrix <- matrix(c(c(1, 2, 3),
                   c(4, 5, 6),
                   c(7, 8, 9)), nrow = 3, ncol = 3)
df <- data.frame(
  name = c("John", "Jane", "Jim", "Jill"),
  age = c(23, 25, 22, 24),
  height = c(180, 170, 175, 160),
  weight = c(75, 65, 70, 55)
)

## Crear lista

In [2]:
# Crear una lista
mylist <- list(vector, matrix, df)
mylist

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
  name age height weight
1 John  23    180     75
2 Jane  25    170     65
3  Jim  22    175     70
4 Jill  24    160     55

## Dar nombre a los elementos de la lista

In [3]:
names(mylist) <- c("vector", "matrix", "df")
mylist

$vector
[1] 1 2 3 4 5

$matrix
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
  name age height weight
1 John  23    180     75
2 Jane  25    170     65
3  Jim  22    175     70
4 Jill  24    160     55

## Acceder a los elementos de la lista

In [5]:
mylist[[1]]        # acceder al vector
mylist[["matrix"]] # acceder a la matriz

[1] 1 2 3 4 5

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

### Acceder al valor del elemento de la lista

In [6]:
mylist[[1]][2]           # acceder a [2] del vector
mylist[["matrix"]][2, 2] # acceder a la posición [2,2] de la matriz
mylist[["df"]][, "age"]  # acceder a la columna "age" del dataframe

[1] 2

[1] 5

[1] 23 25 22 24

## Modificar

In [8]:
mylist[[1]][2] <- 99 # cambiar el valor de la posición [2] del vector
mylist

$vector
[1]  1 99  3  4  5

$matrix
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
  name age height weight
1 John  23    180     75
2 Jane  25    170     65
3  Jim  22    175     70
4 Jill  24    160     55

In [9]:
mylist[[1]] <- NULL # eliminar el vector
mylist

$matrix
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
  name age height weight
1 John  23    180     75
2 Jane  25    170     65
3  Jim  22    175     70
4 Jill  24    160     55