# Array

Importar Librerias

In [29]:
import array as arr
import numpy as np

Vector usando la libreria "array"

In [30]:
vector = arr.array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for arr in vector:
    print(arr, end=' ')

1 2 3 4 5 6 7 8 9 10 

Vectores usando numpy

In [31]:
v1  = np.array([1,2,3,4,5])
v2  = np.array([6,7,8,9,10])
print("v1 = ",v1)
print("v2 = ",v2)

v1 =  [1 2 3 4 5]
v2 =  [ 6  7  8  9 10]


Suma de dos vectores

In [32]:
print("v1 + v2 = ",v1 + v2)

v1 + v2 =  [ 7  9 11 13 15]


---

De Listas a matrix/array

In [33]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(lista)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Generar una matriz de $dim 2$ (Matriz)


$$
\text{Sea } A = (a_{ij}) \in \mathbb{R}^{n \times m},
\quad \text{  con } a_{ij} \in \mathbb{R},
\quad \text{ donde } n=3, m=5.
$$

In [36]:
n = 3
m = 5
A = np.arange(15).reshape(n,m)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Generar un arreglo de $dim 3$ (Tensor de dimensión 3), donde $n=3$, $m=4$, $p=2$

$$
\text{Sea }T = (t_{ijk}) \in \mathbb{R}^{n \times m \times p},
\quad \text{  con } t_{ijk} \in \mathbb{R},
\quad \text{ donde } n=3, m=5, p=2.
$$

In [35]:
n = 3
m = 4
p = 2
T = np.arange(24).reshape(p,n,m)
print(T)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
