# Axis

Importar numpy e inicializar matrices

In [27]:
import numpy as np

In [28]:
A = np.array([[0,1,2], [4,2,3]])
B = np.array([[1,2,3], [4,5,6]])
print("A = \n",A, "\n")
print("B = \n",B, "\n")

A = 
 [[0 1 2]
 [4 2 3]] 

B = 
 [[1 2 3]
 [4 5 6]] 



Suma del eje $y$ (vertical) de la matriz $A$

In [29]:
print(np.sum(A, axis=0))

[4 3 5]


Suma del eje $x$ (horizontal) de la matriz $A$

In [30]:
print(np.sum(A, axis=1))

[3 9]


Concatenar dos matrices y obtener una sola matriz en el eje $y$ (vertical)

In [31]:
print("A = \n",A, "\n")
print("B = \n",B, "\n")
print("Matrices A y B concatenados:\n", np.concatenate([A,B], axis=0))

A = 
 [[0 1 2]
 [4 2 3]] 

B = 
 [[1 2 3]
 [4 5 6]] 

Matrices A y B concatenados:
 [[0 1 2]
 [4 2 3]
 [1 2 3]
 [4 5 6]]


Concatenar dos matrices y obtener una sola matriz en el eje $x$ (horizontal)

In [32]:
print("A = \n",A, "\n")
print("B = \n",B, "\n")
print("Matrices A y B concatenados:\n", np.concatenate([A,B], axis=1))

A = 
 [[0 1 2]
 [4 2 3]] 

B = 
 [[1 2 3]
 [4 5 6]] 

Matrices A y B concatenados:
 [[0 1 2 1 2 3]
 [4 2 3 4 5 6]]
