# Linear Algebra

In [39]:
import numpy as np

In [40]:
A = np.array([[1,-1,2], [3,2,0]])
A

array([[ 1, -1,  2],
       [ 3,  2,  0]])

Matriz de una sola columna

In [41]:
B = np.array([[1], [2], [3]])
B

array([[1],
       [2],
       [3]])

La transpuesta de un vector $v^T$ y matriz $A^T$

In [42]:
print("v^T = \n", np.transpose(B),   "\n")
print("A^T = \n", np.transpose(A),   "\n")

v^T = 
 [[1 2 3]] 

A^T = 
 [[ 1  3]
 [-1  2]
 [ 2  0]] 



---


### Sistema de ecuaciones $Ax = b$

E1: Resolver el siguiente sistema de ecuaciones:

$$
\begin{aligned}
2x + y - 2z &= -3 \\
3x \quad \quad + z &= 5 \\
x + y - z &= -2
\end{aligned}
$$



In [43]:
A = np.array([[2,1,-2],
              [3,0,1],
              [1,1,-1]])

b = np.array([[-3],[5],[-2]])

print("A = \n",A, "\n")
print("b = \n",b, "\n")

A = 
 [[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]] 

b = 
 [[-3]
 [ 5]
 [-2]] 



Solución y comprobación:

In [44]:
x = np.linalg.solve(A, b)
print("x = \n",x, "\n")
print("Comprobación: ",np.allclose(np.dot(A,x), b))

x = 
 [[ 1.]
 [-1.]
 [ 2.]] 

Comprobación:  True


E2: Resolver el siguiente sistema de ecuaciones:


$$
\begin{aligned}
2x + 7y + 3z &= 1 \\
3x + 8y + 2z &= 1 \\
 x + 3y + z &= 0
\end{aligned}
$$

In [45]:
A = np.array([[2,7,3],
              [2,8,2],
              [1,3,1]])

b = np.array([[1],[1],[0]])

print("A = \n",A, "\n")
print("b = \n",b, "\n")

A = 
 [[2 7 3]
 [2 8 2]
 [1 3 1]] 

b = 
 [[1]
 [1]
 [0]] 



Solución y comprobación

In [46]:
x = np.linalg.solve(A, b)
print("x = \n",x, "\n")
print("Comprobación: ",np.allclose(np.dot(A,x), b))

x = 
 [[-2. ]
 [ 0.5]
 [ 0.5]] 

Comprobación:  True
