# Operations

Importar numpy e inicializar vectores

In [281]:
import numpy as np

In [282]:
v = np.array([1,2,3,4,5])
w = np.array([5,7,1,9,5])
print("v = ",v)
print("w = ",w)

v =  [1 2 3 4 5]
w =  [5 7 1 9 5]


Suma, Resta, Producto en cada elemento $v_i$ = $w_i$

In [283]:
print("v + v = ",       v + w)
print("v - v = ",       v - w)
print("v(i) * w(i) = ", v * w)

v + v =  [ 6  9  4 13 10]
v - v =  [-4 -5  2 -5  0]
v(i) * w(i) =  [ 5 14  3 36 25]


### Usando Numpy

In [284]:
print("v = ",v)
print("w = ",w)

v =  [1 2 3 4 5]
w =  [5 7 1 9 5]


Suma, Resta, Producto y division en cada elemento $v_i = w_i$

In [285]:
print("v + v = ",       np.add(v, w))
print("v - v = ",       np.subtract(v, w))
print("v(i) * w(i) = ", np.multiply(v, w))
print("v(i) / w(i) = ", np.divide(v, w))

v + v =  [ 6  9  4 13 10]
v - v =  [-4 -5  2 -5  0]
v(i) * w(i) =  [ 5 14  3 36 25]
v(i) / w(i) =  [0.2        0.28571429 3.         0.44444444 1.        ]


Potencia en cada elemento $v_i$

In [286]:
np.power(v, 2) #v^2

array([ 1,  4,  9, 16, 25])

In [287]:
np.array(v**2) #v^2

array([ 1,  4,  9, 16, 25])

Operadores Lógicos

In [288]:
print("v = ",v)
print("w = ",w)

v =  [1 2 3 4 5]
w =  [5 7 1 9 5]


In [289]:
print("v1 == v2: ", v == w)
print("v1 != v2: ", v != w)
print("v1 < v2: ",  v < w)  # < , <=
print("v1 >= v2: ", v >= w) # >, >=

v1 == v2:  [False False False False  True]
v1 != v2:  [ True  True  True  True False]
v1 < v2:  [ True  True False  True False]
v1 >= v2:  [False False  True False  True]


Concatenar

In [290]:
print("v = ",v)
print("w = ",w)
print("Concatenación: ",np.concatenate((v,w)))

v =  [1 2 3 4 5]
w =  [5 7 1 9 5]
Concatenación:  [1 2 3 4 5 5 7 1 9 5]


## Operaciones con matrices

$\text{Sean }$
$$
A = (a_{ij}) \in \mathbb{R}^{n \times m},
\quad \text{  con } a_{ij} \in \mathbb{R},
\quad \text{ donde } n=4, m=4.
$$


$$B = (b_{ij}) \in \mathbb{R}^{n \times m},
\quad \text{  con } b_{ij} \in \mathbb{R},
\quad \text{ donde } n=4 , m= 4.
$$

Generando $A$ y $B$

In [291]:
n_A = 4; m_A = 4; n_B = 4; m_B = 4
A = np.arange(16).reshape(n_A, m_A)
B = np.arange(16).reshape(n_B, m_B)

In [292]:
print("A = \n",A)
print("B = \n",B)

A = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
B = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Suma y Restas

Recordar: Para la suma y resta de dos matrices, las matrices deben ser del mismo tamaño

In [293]:
print("A + B: \n", A + B)
print("A - B: \n", A - B)

A + B: 
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
A - B: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Producto de dos matrices (Algebra Lineal)

Recordar:
$$
\text{Sean } A = (a_{ij}) \in \mathbb{R}^{n_A \times m_A} \quad \text{ y } \quad  B = (b_{ij}) \in \mathbb{R}^{n_B \times m_B} \quad \text{ matrices.}
$$

$$A \times B = (x_{ij}) \in \mathbb{R}^{n_A \times m_B},
\quad \text{  donde } m_A = n_B.
$$


In [294]:
n_A = 4; m_A = 4; n_B = 4; m_B = 5
A = np.arange(16).reshape(n_A, m_A)
B = np.arange(20).reshape(n_B, m_B)
print("A = \n",A)
print("B = \n",B)

A = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
B = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [295]:
print("A x B =\n", A.dot(B))

A x B =
 [[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]
 [430 484 538 592 646]]
