# Random

In [13]:
import numpy as np

Números aleatorios Enteros

In [14]:
v = np.random.randint(10) # Intervalo de [0, 10] Enteros
v

9

In [15]:
w = np.random.randint(1,15) # Intervalo de [1, 15] Enteros
w

7

In [16]:
A = np.random.randint(10, size=(3,4)) # Matriz de 3x4 con valores entre [0, 10]
A

array([[3, 6, 1, 5],
       [2, 9, 3, 4],
       [2, 3, 9, 3]])

Números aleatorios flotantes

In [17]:
v = np.random.rand(5) # 5 números flotantes aleatorios entre [0, 1]
v

array([0.40786955, 0.12340584, 0.28534329, 0.79818664, 0.99738719])

In [18]:
A = np.random.rand(3,3) # Matriz de 3x3 con valores entre [0, 1]
A

array([[0.3474686 , 0.17575596, 0.1038248 ],
       [0.93741304, 0.78764694, 0.77337205],
       [0.23769086, 0.83745329, 0.98102008]])

Obtener un número aleatorio

In [19]:
v = np.random.choice([1,2,3,4,5,6,7,8,9,10])
v

1

In [20]:
A = np.random.choice([1,2,3,4,5,6,7,8,9,10], size=(3,3)) # Matriz 3x3 con valores entre [1, 10]
A

array([[2, 5, 9],
       [9, 2, 6],
       [2, 4, 5]])