# Random

In [17]:
import numpy as np

## Números aleatorios Enteros

In [18]:
v = np.random.randint(10) # Intervalo de [0, 10] Enteros
v

2

In [19]:
w = np.random.randint(1,15) # Intervalo de [1, 15] Enteros
w

14

In [20]:
A = np.random.randint(10, size=(3,4)) # Matriz de 3x4 con valores entre [0, 10]
A

array([[0, 8, 4, 3],
       [0, 7, 1, 4],
       [4, 4, 9, 5]])

## Números aleatorios flotantes

In [21]:
v = np.random.rand(5) # 5 números flotantes aleatorios entre [0, 1]
v

array([0.41378868, 0.25219083, 0.00662809, 0.12942723, 0.9461247 ])

In [22]:
A = np.random.rand(3,3) # Matriz de 3x3 con valores entre [0, 1]
A

array([[0.73390232, 0.30075173, 0.56251646],
       [0.82804304, 0.59535978, 0.12847651],
       [0.82195234, 0.99454253, 0.27160385]])

## Obtener un número aleatorio

In [23]:
v = np.random.choice([1,2,3,4,5,6,7,8,9,10])
v

4

In [24]:
A = np.random.choice([1,2,3,4,5,6,7,8,9,10], size=(3,3)) # Matriz 3x3 con valores entre [1, 10]
A

array([[4, 2, 8],
       [2, 3, 4],
       [6, 9, 1]])